/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LearningDevelopmentRouteImport } from './routes/learning-development'
import { Route as HrContactRouteImport } from './routes/hr-contact'
import { Route as CompensationBenefitsRouteImport } from './routes/compensation-benefits'
import { Route as CompanyPoliciesRouteImport } from './routes/company-policies'
import { Route as CompanyIntroductionRouteImport } from './routes/company-introduction'
import { Route as CommunicationToolsRouteImport } from './routes/communication-tools'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as IndexRouteImport } from './routes/index'

const LearningDevelopmentRoute = LearningDevelopmentRouteImport.update({
  id: '/learning-development',
  path: '/learning-development',
  getParentRoute: () => rootRouteImport,
} as any)
const HrContactRoute = HrContactRouteImport.update({
  id: '/hr-contact',
  path: '/hr-contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompensationBenefitsRoute = CompensationBenefitsRouteImport.update({
  id: '/compensation-benefits',
  path: '/compensation-benefits',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyPoliciesRoute = CompanyPoliciesRouteImport.update({
  id: '/company-policies',
  path: '/company-policies',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyIntroductionRoute = CompanyIntroductionRouteImport.update({
  id: '/company-introduction',
  path: '/company-introduction',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationToolsRoute = CommunicationToolsRouteImport.update({
  id: '/communication-tools',
  path: '/communication-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checklist': typeof ChecklistRoute
  '/communication-tools': typeof CommunicationToolsRoute
  '/company-introduction': typeof CompanyIntroductionRoute
  '/company-policies': typeof CompanyPoliciesRoute
  '/compensation-benefits': typeof CompensationBenefitsRoute
  '/hr-contact': typeof HrContactRoute
  '/learning-development': typeof LearningDevelopmentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checklist': typeof ChecklistRoute
  '/communication-tools': typeof CommunicationToolsRoute
  '/company-introduction': typeof CompanyIntroductionRoute
  '/company-policies': typeof CompanyPoliciesRoute
  '/compensation-benefits': typeof CompensationBenefitsRoute
  '/hr-contact': typeof HrContactRoute
  '/learning-development': typeof LearningDevelopmentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checklist': typeof ChecklistRoute
  '/communication-tools': typeof CommunicationToolsRoute
  '/company-introduction': typeof CompanyIntroductionRoute
  '/company-policies': typeof CompanyPoliciesRoute
  '/compensation-benefits': typeof CompensationBenefitsRoute
  '/hr-contact': typeof HrContactRoute
  '/learning-development': typeof LearningDevelopmentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checklist'
    | '/communication-tools'
    | '/company-introduction'
    | '/company-policies'
    | '/compensation-benefits'
    | '/hr-contact'
    | '/learning-development'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checklist'
    | '/communication-tools'
    | '/company-introduction'
    | '/company-policies'
    | '/compensation-benefits'
    | '/hr-contact'
    | '/learning-development'
  id:
    | '__root__'
    | '/'
    | '/checklist'
    | '/communication-tools'
    | '/company-introduction'
    | '/company-policies'
    | '/compensation-benefits'
    | '/hr-contact'
    | '/learning-development'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChecklistRoute: typeof ChecklistRoute
  CommunicationToolsRoute: typeof CommunicationToolsRoute
  CompanyIntroductionRoute: typeof CompanyIntroductionRoute
  CompanyPoliciesRoute: typeof CompanyPoliciesRoute
  CompensationBenefitsRoute: typeof CompensationBenefitsRoute
  HrContactRoute: typeof HrContactRoute
  LearningDevelopmentRoute: typeof LearningDevelopmentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/learning-development': {
      id: '/learning-development'
      path: '/learning-development'
      fullPath: '/learning-development'
      preLoaderRoute: typeof LearningDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr-contact': {
      id: '/hr-contact'
      path: '/hr-contact'
      fullPath: '/hr-contact'
      preLoaderRoute: typeof HrContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compensation-benefits': {
      id: '/compensation-benefits'
      path: '/compensation-benefits'
      fullPath: '/compensation-benefits'
      preLoaderRoute: typeof CompensationBenefitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-policies': {
      id: '/company-policies'
      path: '/company-policies'
      fullPath: '/company-policies'
      preLoaderRoute: typeof CompanyPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-introduction': {
      id: '/company-introduction'
      path: '/company-introduction'
      fullPath: '/company-introduction'
      preLoaderRoute: typeof CompanyIntroductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communication-tools': {
      id: '/communication-tools'
      path: '/communication-tools'
      fullPath: '/communication-tools'
      preLoaderRoute: typeof CommunicationToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChecklistRoute: ChecklistRoute,
  CommunicationToolsRoute: CommunicationToolsRoute,
  CompanyIntroductionRoute: CompanyIntroductionRoute,
  CompanyPoliciesRoute: CompanyPoliciesRoute,
  CompensationBenefitsRoute: CompensationBenefitsRoute,
  HrContactRoute: HrContactRoute,
  LearningDevelopmentRoute: LearningDevelopmentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
